//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;


    public partial class Product
    {
        public Product()
        {
            this.ProductSold = new HashSet<ProductSold>();
        }

        public int ID { get; set; }
        [Display(Name = "Product Name")]
        [Required(ErrorMessage = "Product name is required")]
        [RegularExpression(@"^[a-zA-Z0-9'' ']+$", ErrorMessage = "Special charecters are not allowed")]
        public string Name { get; set; }

        [Display(Name = "Product Price")]
        [Required(ErrorMessage = "Product price is required")]
        public decimal Price { get; set; }

        public virtual ICollection<ProductSold> ProductSold { get; set; }
    }
}
